---
title: "SCED"
subtitle: "Vignette"
author: "Ian Hussey"
output:
  html_document:
    df_print: paged
    highlight: haddock
---

```{r include=FALSE}

knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE)

```

```{r}

# dependencies
library(SCED)
library(knitr)
library(tidyverse)

# dependencies required by SCED
library(broom)
library(coin)
library(survival)
library(effsize)
library(bootES)
library(boot)
library(stringr)
library(timesavers)  # from github/ianhussey

# disable scientific notation
options(scipen = 999) 

```

# Simulate two participants

```{r}

# simulate data
data <- simulate_data(participants = 2,    # two participants
                      timepoints_a = 10,   # 10 timepoints pre 
                      timepoints_b = 10,   # 10 post intervention
                      cohens_d = 1) %>%  # Cohen's d = 1.5
  mutate(Participant = paste("Participant", Participant))

```

```{r}

# analyse
results <- sced_analysis(data = data)

```

```{r}

# sced_summary(results = results) %>%
#   kable()

results %>%
  kable()

```

```{r fig.height=5, fig.width=5}

# plot
sced_plot(data = data)

```

# Use in-built dataset that's a little more complex

```{r}

# analyse
results <- sced_analysis(data = simulated_data)

```

```{r}

# # summarise results in a table
# sced_summary(results = results) %>%
#   kable()

# summarise results in a table
results %>%
  kable()

```


```{r fig.height=10, fig.width=5}

# plot
sced_plot(data = simulated_data)

```

```{r}

# meta analysis
meta_analysis <- sced_meta_analysis(results = results)

# forest plot
forest(meta_analysis$model_fit, 
       xlab = "Odds ratio",
       digits = 2,
       atransf = exp,
       addcred = TRUE) 

```

`r meta_analysis$meta_effect`

`r meta_analysis$meta_heterogeneity`


