---
title: "SCED"
subtitle: "Development of meta analysis function"
author: "Ian Hussey"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE,
                      cache.lazy=TRUE)
```

```{r}

# dependencies
# library(devtools)
# install_github("ianhussey/SCED")
# install_github("ianhussey/timesavers")
library(SCED)  # from github/ianhussey
library(knitr)
library(tidyverse)

# dependencies required by SCED package
library(broom)
library(coin)
library(survival)
library(effsize)
library(bootES)
library(boot)
library(stringr)
library(timesavers)  # from github/ianhussey

# disable scientific notation
options(scipen = 999) 

# simulate data
data <- simulate_data(participants = 8,    # two participants
                      timepoints_a = 10,   # 10 timepoints pre 
                      timepoints_b = 10,   # 10 post intervention
                      cohens_d = 1.5) %>%  # Cohen's d = 1.5
  mutate(Participant = paste("Participant", Participant))

# analyse
results <- sced_analysis(data = data)

# meta analysis
meta_analysis <- sced_meta_analysis(results = results)

# Forest plot
forest(meta_analysis$model_fit,
       xlab = "Ruscio's A",
       digits = 2,
       addcred = TRUE,
       refline = 0.5)
## add column headings to the plot
text(-6.3, 6.8, "Participant", pos = 4)
text( 8.4, 6.8, "Ruscio's A [95% CI]", pos = 2)

```

`r meta_analysis$meta_effect`

`r meta_analysis$meta_heterogeneity`